/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_adapter_gpio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* PIO0, 0 signal defines */
/* Definition of the pin port */
#define BOARD_INITPINS_PIO0_0_PORT 0U
/* Definition of the pin number */
#define BOARD_INITPINS_PIO0_0_PIN 0U
/* Definition of the pin direction */
#define BOARD_INITPINS_PIO0_0_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_PIO0_0_PIN_LEVEL 0U
/* PIO0, 1 signal defines */
/* Definition of the pin port */
#define BOARD_INITPINS_PIO0_1_PORT 0U
/* Definition of the pin number */
#define BOARD_INITPINS_PIO0_1_PIN 1U
/* Definition of the pin direction */
#define BOARD_INITPINS_PIO0_1_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_PIO0_1_PIN_LEVEL 0U

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_PIO0_0_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_PIO0_1_handle);

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(uint8_t port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
